### ISSUE TITLE
CustomEvent does not have what gets copied in `details`

### ISSUE THREAD

**Issue by dhruvin2910** [github/clipboard-copy-element#23]
It'd be great if the element also provided the text it copies, in the `event.details`.

Currently, if you use multiple clipboard-copy elements on a page, with various ways to define what to copy (i.e. `for="..."` or `value="..."`), and you want to get what is copied using `clipboard-copy` custom event, you'd have to write your event handler to handle all aforementioned cases.

Passing `value` in `details` simplifies the code for event-listeners.

**Comment by muan** [comment]
@dhruvin2910 could you provide an example of how this would be used?

**Comment by dhruvin2910** [comment]
Sure. I'd like to add native clipboard support to dev.to's android application, which is using webview. They are using this package for web, and that works great. But for webview, there's a bridge between javascript and kotlin implementation of ClipBoard Manager.

Here, I can use clipboard-copy event to trigger that native implementation. But to get the "to be copied" value, I'll have to find where the value is in the dom. Plus some views use `a[href]` version and some use `input.value` version. So it'll be better if I can get the value directly form the event, and pass it as is to the native implementation.

**Comment by muan** [comment]
@dhruvin2910 Thanks, am I understanding correctly that it's used as a fallback when the value needs to be copied by other means?

The custom event is supposed to be fired **after** the copy action succeeded. Your proposed PR is dependent on the Promise to _resolve successfully_, and return the value. It but the promisse should not resolve and dispatch an event, if the copy action didn't succeed. 

So I guess my question is: Is this failing silently without exception in Android webview?

A more neutral approach in my opinion would be to expose this value through a getter on `<clipboard-copy>`, this way it can be retrieved without depending on a copy action's state. However, this might require more discussions since it could change the code structure quite a bit.

**Comment by dhruvin2910** [comment]
> @dhruvin2910 Thanks, am I understanding correctly that it's used as a fallback when the value needs to be copied by other means?

Yes.

> So I guess my question is: Is this failing silently without exception in Android webview?

I have limited experience with webview. I have not tested it personally yet, but I assumed that from [this issue](https://github.com/thepracticaldev/dev.to/issues/4543). I think there must be another way to have clipboard support. But this solves the problem fine.

> A more neutral approach in my opinion would be to expose this value through a getter on <clipboard-copy>, this way it can be retrieved without depending on a copy action's state. However, this might require more discussions since it could change the code structure quite a bit.

I agree. Initially I modified the getter and setter of the value property of the element. But I did not know what I would be breaking. So I decided to go with this version instead.

**Comment by muan** [comment]
@dhruvin2910 Thanks for answering these questions. I discussed this with @dgraham, and we came to the conclusion to close this for now, given 

> Hence clipboard-copy should be working as expected.

For what it's worth, the feature you proposed in #24 does seem potentially useful, but in general we strive to only add code with clear use cases, because every feature adds onto the burden for maintainers.

We'd be happy to re-assess if such use case is presented. 

For now, it sounded like the issue you're facing could potentially be fixed by a polyfill/patch for  `navigator.clipboard.writeText`.
