### ISSUE TITLE
Distribute on a CDN

### ISSUE THREAD

**Issue by hirusi** [github/clipboard-copy-element#37]
I use a WordPress blog and would like to add this to my site. I imagined it would be as simple as adding a script tag from a CDN and using the element. After all, that's the point of a web component.

Distributing the dist on a CDN would be a good idea for such use cases where you don't have a module bundler or want to avoid an npm installation for just one package.

**Comment by koddsson** [comment]
We use unpkg for this on the demo site. Can you use something like that?

https://github.com/github/clipboard-copy-element/blob/4969cf8c11a71759d06da2afa1318d67e44513f1/examples/index.html#L5

**Comment by hirusi** [comment]
Oh, sure! That works for me. Perhaps be nice to document it in the README? What do you think?

**Comment by koddsson** [comment]
I hesitate because we don't control that service, and we're going to have to update all the README's that reference it if it ever goes away. I'd much rather distribute the library on github and npm and leave how to include the library in their application up to the implementors.

**Comment by keithamus** [comment]
I agree with @koddsson here. I would also add that there are many CDNs which are available to use, such as JSDelivr, Unpkg, CDNJS... promoting one over any others might be considered an endorsement of that CDN by our team or by GitHub writ large, it could also be seen as an endorsement of hot linking code to CDNs in general, which is a practice I personally wouldn't like to endorse. 

I think I'll close this issue because the original question has been answered, and I don't think there is anything more actionable here. Thanks everyone!
